SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ORDER_SEQ
    START WITH 1000
    INCREMENT BY 1
    CACHE 20 NOCYCLE';

    EXECUTE IMMEDIATE 'CREATE TABLE ORDERS_77(
        ID NUMBER PRIMARY KEY,
        CUST_NAME VARCHAR2(20),
        ORDER_DATE DATE,
        TOTAL_AMOUNT NUMBER(6)
    )';

EXCEPTION
    WHEN OTHERS THEN  
        EXECUTE IMMEDIATE 'DROP TABLE ORDERS_77'; 
        DBMS_OUTPUT.PUT_LINE('TABLE DROPPED');

        EXECUTE IMMEDIATE 'DROP SEQUENCE ORDER_SEQ';
        DBMS_OUTPUT.PUT_LINE('SEQUENCE DROPPED');
END;
/

DESC ORDERS_77;