SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE INSERT_LOC(
    LOCATION_ID IN NUMBER, 
    STREET_ADDRESS IN VARCHAR2,
    PIN_CODE IN NUMBER(6),
    CITY IN VARCHAR2,
    STATE_PROVINCE IN VARCHAR2,
    COUNTRY_ID IN VARCHAR2
) AS
BEGIN
    INSERT INTO LOCATIONS(LOCATION_ID,STREET_ADDRESS,PIN_CODE,CITY,STATE_PROVINCE,COUNTRY_ID)
    VALUES(LOCATION_ID,STREET_ADDRESS,PIN_CODE,CITY,STATE_PROVINCE,COUNTRY_ID);
END INSERT_LOC;
/

BEGIN
    INSERT_LOC(
        &LOCATION_ID,
        '&STREET_ADDRESS',
        &PINCODE,'&CITY',
        '&STATE_PROVINCE',
        '&COUNTRY_ID');

    DBMS_OUTPUT.PUT_LINE('1 ROW INSERTED!');

END;
/
    SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE INSERT_LOC(
    LOCATION_ID IN NUMBER, 
    STREET_ADDRESS IN VARCHAR2,
    PIN_CODE IN NUMBER(6),
    CITY IN VARCHAR2,
    STATE_PROVINCE IN VARCHAR2,
    COUNTRY_ID IN VARCHAR2
) AS
BEGIN
    INSERT INTO LOCATIONS(LOCATION_ID,STREET_ADDRESS,PIN_CODE,CITY,STATE_PROVINCE,COUNTRY_ID)
    VALUES(LOCATION_ID,STREET_ADDRESS,PIN_CODE,CITY,STATE_PROVINCE,COUNTRY_ID);
END INSERT_LOC;
/

BEGIN
    INSERT_LOC(
        &LOCATION_ID,
        '&STREET_ADDRESS',
        &PINCODE,'&CITY',
        '&STATE_PROVINCE',
        '&COUNTRY_ID')

    DBMS_OUTPUT.PUT_LINE('1 ROW INSERTED!');

END;
/

SELECT * FROM LOCATIONS WHERE LOCATION_ID = 77;