-- MAKE SURE YOU HAVE ORACLE 21C HR SCHEMA INSTALLED.

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE count_emp(regionname IN VARCHAR2,totalrows OUT NUMBER) AS
BEGIN
    SELECT COUNT(*) INTO totalrows FROM EMPLOYEES WHERE EMPLOYEE_ID IN
    (SELECT EMPLOYEE_ID FROM JOB_HISTORY WHERE DEPARTMENT_ID IN
    (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID IN 
    (SELECT LOCATION_ID FROM LOCATIONS WHERE COUNTRY_ID IN
    (SELECT COUNTRY_ID FROM COUNTRIES WHERE REGION_ID IN
    (SELECT REGION_ID FROM REGIONS WHERE REGION_NAME = regionname)))));

    DBMS_OUTPUT.PUT_LINE('TOTAL NUMBER OF RECORDS : '|| totalrows);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('UNKNOWN ERROR OCCUREED');
END count_emp;
/